//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Chambix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaServiciosEntities : DbContext
    {
        public SistemaServiciosEntities()
            : base("name=SistemaServiciosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_Categoria> tb_Categoria { get; set; }
        public virtual DbSet<tb_Distrito> tb_Distrito { get; set; }
        public virtual DbSet<tb_Post> tb_Post { get; set; }
        public virtual DbSet<tb_Replica> tb_Replica { get; set; }
        public virtual DbSet<tb_Servicio> tb_Servicio { get; set; }
        public virtual DbSet<tb_SubCategoria> tb_SubCategoria { get; set; }
        public virtual DbSet<tb_Testimonio> tb_Testimonio { get; set; }
        public virtual DbSet<tb_TipoCuenta> tb_TipoCuenta { get; set; }
        public virtual DbSet<tb_Usuario> tb_Usuario { get; set; }
    }
}
