//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Chambix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Replica
    {
        public int idReplica { get; set; }
        public int idUsuario { get; set; }
        public int idTestimonio { get; set; }
        public string tituloReplica { get; set; }
        public string descripcionReplica { get; set; }
        public Nullable<bool> estadoReplica { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public string update_by { get; set; }
    
        public virtual tb_Testimonio tb_Testimonio { get; set; }
        public virtual tb_Usuario tb_Usuario { get; set; }
    }
}
