//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Chambix.ServicioSubCategoria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubCategoriaBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Chambix")]
    [System.SerializableAttribute()]
    public partial class SubCategoriaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_byField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idSubCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreSubCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime update_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string update_byField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_at {
            get {
                return this.create_atField;
            }
            set {
                if ((this.create_atField.Equals(value) != true)) {
                    this.create_atField = value;
                    this.RaisePropertyChanged("create_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string create_by {
            get {
                return this.create_byField;
            }
            set {
                if ((object.ReferenceEquals(this.create_byField, value) != true)) {
                    this.create_byField = value;
                    this.RaisePropertyChanged("create_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idSubCategoria {
            get {
                return this.idSubCategoriaField;
            }
            set {
                if ((this.idSubCategoriaField.Equals(value) != true)) {
                    this.idSubCategoriaField = value;
                    this.RaisePropertyChanged("idSubCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreSubCategoria {
            get {
                return this.nombreSubCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreSubCategoriaField, value) != true)) {
                    this.nombreSubCategoriaField = value;
                    this.RaisePropertyChanged("nombreSubCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime update_at {
            get {
                return this.update_atField;
            }
            set {
                if ((this.update_atField.Equals(value) != true)) {
                    this.update_atField = value;
                    this.RaisePropertyChanged("update_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string update_by {
            get {
                return this.update_byField;
            }
            set {
                if ((object.ReferenceEquals(this.update_byField, value) != true)) {
                    this.update_byField = value;
                    this.RaisePropertyChanged("update_by");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSubCategoria.IServicioSubCategoria")]
    public interface IServicioSubCategoria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSubCategoria/GetAllSubCategoria", ReplyAction="http://tempuri.org/IServicioSubCategoria/GetAllSubCategoriaResponse")]
        WEB_Chambix.ServicioSubCategoria.SubCategoriaBE[] GetAllSubCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSubCategoria/GetAllSubCategoria", ReplyAction="http://tempuri.org/IServicioSubCategoria/GetAllSubCategoriaResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioSubCategoria.SubCategoriaBE[]> GetAllSubCategoriaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSubCategoriaChannel : WEB_Chambix.ServicioSubCategoria.IServicioSubCategoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSubCategoriaClient : System.ServiceModel.ClientBase<WEB_Chambix.ServicioSubCategoria.IServicioSubCategoria>, WEB_Chambix.ServicioSubCategoria.IServicioSubCategoria {
        
        public ServicioSubCategoriaClient() {
        }
        
        public ServicioSubCategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSubCategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSubCategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSubCategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB_Chambix.ServicioSubCategoria.SubCategoriaBE[] GetAllSubCategoria() {
            return base.Channel.GetAllSubCategoria();
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioSubCategoria.SubCategoriaBE[]> GetAllSubCategoriaAsync() {
            return base.Channel.GetAllSubCategoriaAsync();
        }
    }
}
