//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Chambix.ServicioTestimonio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestimonioBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Chambix")]
    [System.SerializableAttribute()]
    public partial class TestimonioBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_byField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionTestimonioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoTestimonioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTestimonioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloTestimonioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime update_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string update_byField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoUsuario {
            get {
                return this.ApellidoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoUsuarioField, value) != true)) {
                    this.ApellidoUsuarioField = value;
                    this.RaisePropertyChanged("ApellidoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_at {
            get {
                return this.create_atField;
            }
            set {
                if ((this.create_atField.Equals(value) != true)) {
                    this.create_atField = value;
                    this.RaisePropertyChanged("create_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string create_by {
            get {
                return this.create_byField;
            }
            set {
                if ((object.ReferenceEquals(this.create_byField, value) != true)) {
                    this.create_byField = value;
                    this.RaisePropertyChanged("create_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionTestimonio {
            get {
                return this.descripcionTestimonioField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionTestimonioField, value) != true)) {
                    this.descripcionTestimonioField = value;
                    this.RaisePropertyChanged("descripcionTestimonio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estadoTestimonio {
            get {
                return this.estadoTestimonioField;
            }
            set {
                if ((this.estadoTestimonioField.Equals(value) != true)) {
                    this.estadoTestimonioField = value;
                    this.RaisePropertyChanged("estadoTestimonio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPost {
            get {
                return this.idPostField;
            }
            set {
                if ((this.idPostField.Equals(value) != true)) {
                    this.idPostField = value;
                    this.RaisePropertyChanged("idPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTestimonio {
            get {
                return this.idTestimonioField;
            }
            set {
                if ((this.idTestimonioField.Equals(value) != true)) {
                    this.idTestimonioField = value;
                    this.RaisePropertyChanged("idTestimonio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tituloTestimonio {
            get {
                return this.tituloTestimonioField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloTestimonioField, value) != true)) {
                    this.tituloTestimonioField = value;
                    this.RaisePropertyChanged("tituloTestimonio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime update_at {
            get {
                return this.update_atField;
            }
            set {
                if ((this.update_atField.Equals(value) != true)) {
                    this.update_atField = value;
                    this.RaisePropertyChanged("update_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string update_by {
            get {
                return this.update_byField;
            }
            set {
                if ((object.ReferenceEquals(this.update_byField, value) != true)) {
                    this.update_byField = value;
                    this.RaisePropertyChanged("update_by");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioTestimonio.IServicioTestimonio")]
    public interface IServicioTestimonio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/InsertTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/InsertTestimonioResponse")]
        bool InsertTestimonio(short idUsuario, short idPost, string tituloTestimonio, string descripcionTestimonio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/InsertTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/InsertTestimonioResponse")]
        System.Threading.Tasks.Task<bool> InsertTestimonioAsync(short idUsuario, short idPost, string tituloTestimonio, string descripcionTestimonio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/UpdateTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/UpdateTestimonioResponse")]
        bool UpdateTestimonio(WEB_Chambix.ServicioTestimonio.TestimonioBE objTestimonioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/UpdateTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/UpdateTestimonioResponse")]
        System.Threading.Tasks.Task<bool> UpdateTestimonioAsync(WEB_Chambix.ServicioTestimonio.TestimonioBE objTestimonioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/DeleteTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/DeleteTestimonioResponse")]
        bool DeleteTestimonio(int idTestimonio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/DeleteTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/DeleteTestimonioResponse")]
        System.Threading.Tasks.Task<bool> DeleteTestimonioAsync(int idTestimonio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/GetTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/GetTestimonioResponse")]
        WEB_Chambix.ServicioTestimonio.TestimonioBE GetTestimonio(int idTestimonio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/GetTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/GetTestimonioResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioTestimonio.TestimonioBE> GetTestimonioAsync(int idTestimonio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/GetAllTestimonioId", ReplyAction="http://tempuri.org/IServicioTestimonio/GetAllTestimonioIdResponse")]
        WEB_Chambix.ServicioTestimonio.TestimonioBE[] GetAllTestimonioId(int idPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/GetAllTestimonioId", ReplyAction="http://tempuri.org/IServicioTestimonio/GetAllTestimonioIdResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioTestimonio.TestimonioBE[]> GetAllTestimonioIdAsync(int idPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/GetContarTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/GetContarTestimonioResponse")]
        short GetContarTestimonio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/GetContarTestimonio", ReplyAction="http://tempuri.org/IServicioTestimonio/GetContarTestimonioResponse")]
        System.Threading.Tasks.Task<short> GetContarTestimonioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/GetContarTestimonioIdUsuario", ReplyAction="http://tempuri.org/IServicioTestimonio/GetContarTestimonioIdUsuarioResponse")]
        short GetContarTestimonioIdUsuario(short idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTestimonio/GetContarTestimonioIdUsuario", ReplyAction="http://tempuri.org/IServicioTestimonio/GetContarTestimonioIdUsuarioResponse")]
        System.Threading.Tasks.Task<short> GetContarTestimonioIdUsuarioAsync(short idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioTestimonioChannel : WEB_Chambix.ServicioTestimonio.IServicioTestimonio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTestimonioClient : System.ServiceModel.ClientBase<WEB_Chambix.ServicioTestimonio.IServicioTestimonio>, WEB_Chambix.ServicioTestimonio.IServicioTestimonio {
        
        public ServicioTestimonioClient() {
        }
        
        public ServicioTestimonioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTestimonioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTestimonioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTestimonioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertTestimonio(short idUsuario, short idPost, string tituloTestimonio, string descripcionTestimonio) {
            return base.Channel.InsertTestimonio(idUsuario, idPost, tituloTestimonio, descripcionTestimonio);
        }
        
        public System.Threading.Tasks.Task<bool> InsertTestimonioAsync(short idUsuario, short idPost, string tituloTestimonio, string descripcionTestimonio) {
            return base.Channel.InsertTestimonioAsync(idUsuario, idPost, tituloTestimonio, descripcionTestimonio);
        }
        
        public bool UpdateTestimonio(WEB_Chambix.ServicioTestimonio.TestimonioBE objTestimonioBE) {
            return base.Channel.UpdateTestimonio(objTestimonioBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTestimonioAsync(WEB_Chambix.ServicioTestimonio.TestimonioBE objTestimonioBE) {
            return base.Channel.UpdateTestimonioAsync(objTestimonioBE);
        }
        
        public bool DeleteTestimonio(int idTestimonio) {
            return base.Channel.DeleteTestimonio(idTestimonio);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTestimonioAsync(int idTestimonio) {
            return base.Channel.DeleteTestimonioAsync(idTestimonio);
        }
        
        public WEB_Chambix.ServicioTestimonio.TestimonioBE GetTestimonio(int idTestimonio) {
            return base.Channel.GetTestimonio(idTestimonio);
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioTestimonio.TestimonioBE> GetTestimonioAsync(int idTestimonio) {
            return base.Channel.GetTestimonioAsync(idTestimonio);
        }
        
        public WEB_Chambix.ServicioTestimonio.TestimonioBE[] GetAllTestimonioId(int idPost) {
            return base.Channel.GetAllTestimonioId(idPost);
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioTestimonio.TestimonioBE[]> GetAllTestimonioIdAsync(int idPost) {
            return base.Channel.GetAllTestimonioIdAsync(idPost);
        }
        
        public short GetContarTestimonio() {
            return base.Channel.GetContarTestimonio();
        }
        
        public System.Threading.Tasks.Task<short> GetContarTestimonioAsync() {
            return base.Channel.GetContarTestimonioAsync();
        }
        
        public short GetContarTestimonioIdUsuario(short idUsuario) {
            return base.Channel.GetContarTestimonioIdUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<short> GetContarTestimonioIdUsuarioAsync(short idUsuario) {
            return base.Channel.GetContarTestimonioIdUsuarioAsync(idUsuario);
        }
    }
}
