//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Chambix.ServicioUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Chambix")]
    [System.SerializableAttribute()]
    public partial class UserBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cellUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_byField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short estadoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idTipoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ocupacionUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short rankUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tiempoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short tipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime update_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string update_byField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wspUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoUsuario {
            get {
                return this.apellidoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoUsuarioField, value) != true)) {
                    this.apellidoUsuarioField = value;
                    this.RaisePropertyChanged("apellidoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cellUsuario {
            get {
                return this.cellUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.cellUsuarioField, value) != true)) {
                    this.cellUsuarioField = value;
                    this.RaisePropertyChanged("cellUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenaUsuario {
            get {
                return this.contrasenaUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaUsuarioField, value) != true)) {
                    this.contrasenaUsuarioField = value;
                    this.RaisePropertyChanged("contrasenaUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_at {
            get {
                return this.create_atField;
            }
            set {
                if ((this.create_atField.Equals(value) != true)) {
                    this.create_atField = value;
                    this.RaisePropertyChanged("create_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string create_by {
            get {
                return this.create_byField;
            }
            set {
                if ((object.ReferenceEquals(this.create_byField, value) != true)) {
                    this.create_byField = value;
                    this.RaisePropertyChanged("create_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailUsuario {
            get {
                return this.emailUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.emailUsuarioField, value) != true)) {
                    this.emailUsuarioField = value;
                    this.RaisePropertyChanged("emailUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short estadoUsuario {
            get {
                return this.estadoUsuarioField;
            }
            set {
                if ((this.estadoUsuarioField.Equals(value) != true)) {
                    this.estadoUsuarioField = value;
                    this.RaisePropertyChanged("estadoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                if ((this.idDistritoField.Equals(value) != true)) {
                    this.idDistritoField = value;
                    this.RaisePropertyChanged("idDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idTipoCuenta {
            get {
                return this.idTipoCuentaField;
            }
            set {
                if ((this.idTipoCuentaField.Equals(value) != true)) {
                    this.idTipoCuentaField = value;
                    this.RaisePropertyChanged("idTipoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ocupacionUsuario {
            get {
                return this.ocupacionUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ocupacionUsuarioField, value) != true)) {
                    this.ocupacionUsuarioField = value;
                    this.RaisePropertyChanged("ocupacionUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short rankUsuario {
            get {
                return this.rankUsuarioField;
            }
            set {
                if ((this.rankUsuarioField.Equals(value) != true)) {
                    this.rankUsuarioField = value;
                    this.RaisePropertyChanged("rankUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tiempoCuenta {
            get {
                return this.tiempoCuentaField;
            }
            set {
                if ((this.tiempoCuentaField.Equals(value) != true)) {
                    this.tiempoCuentaField = value;
                    this.RaisePropertyChanged("tiempoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                if ((this.tipoUsuarioField.Equals(value) != true)) {
                    this.tipoUsuarioField = value;
                    this.RaisePropertyChanged("tipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime update_at {
            get {
                return this.update_atField;
            }
            set {
                if ((this.update_atField.Equals(value) != true)) {
                    this.update_atField = value;
                    this.RaisePropertyChanged("update_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string update_by {
            get {
                return this.update_byField;
            }
            set {
                if ((object.ReferenceEquals(this.update_byField, value) != true)) {
                    this.update_byField = value;
                    this.RaisePropertyChanged("update_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string wspUsuario {
            get {
                return this.wspUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.wspUsuarioField, value) != true)) {
                    this.wspUsuarioField = value;
                    this.RaisePropertyChanged("wspUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuario.IServicioUsuario")]
    public interface IServicioUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/InsertUser", ReplyAction="http://tempuri.org/IServicioUsuario/InsertUserResponse")]
        bool InsertUser(string nombreUsuario, string apellidoUsuario, string contrasenaUsuario, short idDistrito, string emailUsuario, string cellUsuario, string wspUsuario, string ocupacionUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/InsertUser", ReplyAction="http://tempuri.org/IServicioUsuario/InsertUserResponse")]
        System.Threading.Tasks.Task<bool> InsertUserAsync(string nombreUsuario, string apellidoUsuario, string contrasenaUsuario, short idDistrito, string emailUsuario, string cellUsuario, string wspUsuario, string ocupacionUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/UpdateUser", ReplyAction="http://tempuri.org/IServicioUsuario/UpdateUserResponse")]
        bool UpdateUser(short idUsuario, string nombreUsuario, string apellidoUsuario, string contrasenaUsuario, short idDistrito, string emailUsuario, string cellUsuario, string wspUsuario, string ocupacionUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/UpdateUser", ReplyAction="http://tempuri.org/IServicioUsuario/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(short idUsuario, string nombreUsuario, string apellidoUsuario, string contrasenaUsuario, short idDistrito, string emailUsuario, string cellUsuario, string wspUsuario, string ocupacionUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/LogicDeleteUser", ReplyAction="http://tempuri.org/IServicioUsuario/LogicDeleteUserResponse")]
        bool LogicDeleteUser(WEB_Chambix.ServicioUsuario.UserBE objUserBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/LogicDeleteUser", ReplyAction="http://tempuri.org/IServicioUsuario/LogicDeleteUserResponse")]
        System.Threading.Tasks.Task<bool> LogicDeleteUserAsync(WEB_Chambix.ServicioUsuario.UserBE objUserBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetUser", ReplyAction="http://tempuri.org/IServicioUsuario/GetUserResponse")]
        WEB_Chambix.ServicioUsuario.UserBE GetUser(short idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetUser", ReplyAction="http://tempuri.org/IServicioUsuario/GetUserResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE> GetUserAsync(short idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsers", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersResponse")]
        WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsers", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsersClients", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersClientsResponse")]
        WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsersClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsersClients", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersClientsResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsersProfesionals", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersProfesionalsResponse")]
        WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsersProfesionals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsersProfesionals", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersProfesionalsResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersProfesionalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsersAdmins", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersAdminsResponse")]
        WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsersAdmins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsersAdmins", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersAdminsResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersAdminsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetContarUsuarios", ReplyAction="http://tempuri.org/IServicioUsuario/GetContarUsuariosResponse")]
        short GetContarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetContarUsuarios", ReplyAction="http://tempuri.org/IServicioUsuario/GetContarUsuariosResponse")]
        System.Threading.Tasks.Task<short> GetContarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsersPostulantes", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersPostulantesResponse")]
        WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsersPostulantes(short idPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/GetAllUsersPostulantes", ReplyAction="http://tempuri.org/IServicioUsuario/GetAllUsersPostulantesResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersPostulantesAsync(short idPost);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioChannel : WEB_Chambix.ServicioUsuario.IServicioUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioClient : System.ServiceModel.ClientBase<WEB_Chambix.ServicioUsuario.IServicioUsuario>, WEB_Chambix.ServicioUsuario.IServicioUsuario {
        
        public ServicioUsuarioClient() {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertUser(string nombreUsuario, string apellidoUsuario, string contrasenaUsuario, short idDistrito, string emailUsuario, string cellUsuario, string wspUsuario, string ocupacionUsuario) {
            return base.Channel.InsertUser(nombreUsuario, apellidoUsuario, contrasenaUsuario, idDistrito, emailUsuario, cellUsuario, wspUsuario, ocupacionUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> InsertUserAsync(string nombreUsuario, string apellidoUsuario, string contrasenaUsuario, short idDistrito, string emailUsuario, string cellUsuario, string wspUsuario, string ocupacionUsuario) {
            return base.Channel.InsertUserAsync(nombreUsuario, apellidoUsuario, contrasenaUsuario, idDistrito, emailUsuario, cellUsuario, wspUsuario, ocupacionUsuario);
        }
        
        public bool UpdateUser(short idUsuario, string nombreUsuario, string apellidoUsuario, string contrasenaUsuario, short idDistrito, string emailUsuario, string cellUsuario, string wspUsuario, string ocupacionUsuario) {
            return base.Channel.UpdateUser(idUsuario, nombreUsuario, apellidoUsuario, contrasenaUsuario, idDistrito, emailUsuario, cellUsuario, wspUsuario, ocupacionUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(short idUsuario, string nombreUsuario, string apellidoUsuario, string contrasenaUsuario, short idDistrito, string emailUsuario, string cellUsuario, string wspUsuario, string ocupacionUsuario) {
            return base.Channel.UpdateUserAsync(idUsuario, nombreUsuario, apellidoUsuario, contrasenaUsuario, idDistrito, emailUsuario, cellUsuario, wspUsuario, ocupacionUsuario);
        }
        
        public bool LogicDeleteUser(WEB_Chambix.ServicioUsuario.UserBE objUserBE) {
            return base.Channel.LogicDeleteUser(objUserBE);
        }
        
        public System.Threading.Tasks.Task<bool> LogicDeleteUserAsync(WEB_Chambix.ServicioUsuario.UserBE objUserBE) {
            return base.Channel.LogicDeleteUserAsync(objUserBE);
        }
        
        public WEB_Chambix.ServicioUsuario.UserBE GetUser(short idUser) {
            return base.Channel.GetUser(idUser);
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE> GetUserAsync(short idUser) {
            return base.Channel.GetUserAsync(idUser);
        }
        
        public WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsersClients() {
            return base.Channel.GetAllUsersClients();
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersClientsAsync() {
            return base.Channel.GetAllUsersClientsAsync();
        }
        
        public WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsersProfesionals() {
            return base.Channel.GetAllUsersProfesionals();
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersProfesionalsAsync() {
            return base.Channel.GetAllUsersProfesionalsAsync();
        }
        
        public WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsersAdmins() {
            return base.Channel.GetAllUsersAdmins();
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersAdminsAsync() {
            return base.Channel.GetAllUsersAdminsAsync();
        }
        
        public short GetContarUsuarios() {
            return base.Channel.GetContarUsuarios();
        }
        
        public System.Threading.Tasks.Task<short> GetContarUsuariosAsync() {
            return base.Channel.GetContarUsuariosAsync();
        }
        
        public WEB_Chambix.ServicioUsuario.UserBE[] GetAllUsersPostulantes(short idPost) {
            return base.Channel.GetAllUsersPostulantes(idPost);
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioUsuario.UserBE[]> GetAllUsersPostulantesAsync(short idPost) {
            return base.Channel.GetAllUsersPostulantesAsync(idPost);
        }
    }
}
