//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Chambix
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Post()
        {
            this.tb_Servicio = new HashSet<tb_Servicio>();
            this.tb_Testimonio = new HashSet<tb_Testimonio>();
        }
    
        public int idPost { get; set; }
        public int idUsuario { get; set; }
        public int idSubcategoria { get; set; }
        public Nullable<byte> idDistrito { get; set; }
        public string tituloPost { get; set; }
        public string descripcionPost { get; set; }
        public Nullable<decimal> precioPost { get; set; }
        public string imagenPost { get; set; }
        public Nullable<int> valoracionPost { get; set; }
        public Nullable<bool> estadoPost { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public string update_by { get; set; }
    
        public virtual tb_Distrito tb_Distrito { get; set; }
        public virtual tb_SubCategoria tb_SubCategoria { get; set; }
        public virtual tb_Usuario tb_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Servicio> tb_Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Testimonio> tb_Testimonio { get; set; }
    }
}
