//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Chambix.ServicioServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Chambix")]
    [System.SerializableAttribute()]
    public partial class ServicioBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_byField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte estadoServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idPostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime update_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string update_byField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_at {
            get {
                return this.create_atField;
            }
            set {
                if ((this.create_atField.Equals(value) != true)) {
                    this.create_atField = value;
                    this.RaisePropertyChanged("create_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string create_by {
            get {
                return this.create_byField;
            }
            set {
                if ((object.ReferenceEquals(this.create_byField, value) != true)) {
                    this.create_byField = value;
                    this.RaisePropertyChanged("create_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte estadoServicio {
            get {
                return this.estadoServicioField;
            }
            set {
                if ((this.estadoServicioField.Equals(value) != true)) {
                    this.estadoServicioField = value;
                    this.RaisePropertyChanged("estadoServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idPost {
            get {
                return this.idPostField;
            }
            set {
                if ((this.idPostField.Equals(value) != true)) {
                    this.idPostField = value;
                    this.RaisePropertyChanged("idPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idServicio {
            get {
                return this.idServicioField;
            }
            set {
                if ((this.idServicioField.Equals(value) != true)) {
                    this.idServicioField = value;
                    this.RaisePropertyChanged("idServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime update_at {
            get {
                return this.update_atField;
            }
            set {
                if ((this.update_atField.Equals(value) != true)) {
                    this.update_atField = value;
                    this.RaisePropertyChanged("update_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string update_by {
            get {
                return this.update_byField;
            }
            set {
                if ((object.ReferenceEquals(this.update_byField, value) != true)) {
                    this.update_byField = value;
                    this.RaisePropertyChanged("update_by");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioServicio.IServicioServicio")]
    public interface IServicioServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServicio/InsertServicio", ReplyAction="http://tempuri.org/IServicioServicio/InsertServicioResponse")]
        bool InsertServicio(short idUsuario, short idPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServicio/InsertServicio", ReplyAction="http://tempuri.org/IServicioServicio/InsertServicioResponse")]
        System.Threading.Tasks.Task<bool> InsertServicioAsync(short idUsuario, short idPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServicio/UpdateServicio", ReplyAction="http://tempuri.org/IServicioServicio/UpdateServicioResponse")]
        bool UpdateServicio(WEB_Chambix.ServicioServicio.ServicioBE objServicioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServicio/UpdateServicio", ReplyAction="http://tempuri.org/IServicioServicio/UpdateServicioResponse")]
        System.Threading.Tasks.Task<bool> UpdateServicioAsync(WEB_Chambix.ServicioServicio.ServicioBE objServicioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServicio/GetServicio", ReplyAction="http://tempuri.org/IServicioServicio/GetServicioResponse")]
        WEB_Chambix.ServicioServicio.ServicioBE GetServicio(short idServicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServicio/GetServicio", ReplyAction="http://tempuri.org/IServicioServicio/GetServicioResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioServicio.ServicioBE> GetServicioAsync(short idServicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServicio/GetAllServicio", ReplyAction="http://tempuri.org/IServicioServicio/GetAllServicioResponse")]
        WEB_Chambix.ServicioServicio.ServicioBE[] GetAllServicio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioServicio/GetAllServicio", ReplyAction="http://tempuri.org/IServicioServicio/GetAllServicioResponse")]
        System.Threading.Tasks.Task<WEB_Chambix.ServicioServicio.ServicioBE[]> GetAllServicioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioServicioChannel : WEB_Chambix.ServicioServicio.IServicioServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioServicioClient : System.ServiceModel.ClientBase<WEB_Chambix.ServicioServicio.IServicioServicio>, WEB_Chambix.ServicioServicio.IServicioServicio {
        
        public ServicioServicioClient() {
        }
        
        public ServicioServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertServicio(short idUsuario, short idPost) {
            return base.Channel.InsertServicio(idUsuario, idPost);
        }
        
        public System.Threading.Tasks.Task<bool> InsertServicioAsync(short idUsuario, short idPost) {
            return base.Channel.InsertServicioAsync(idUsuario, idPost);
        }
        
        public bool UpdateServicio(WEB_Chambix.ServicioServicio.ServicioBE objServicioBE) {
            return base.Channel.UpdateServicio(objServicioBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateServicioAsync(WEB_Chambix.ServicioServicio.ServicioBE objServicioBE) {
            return base.Channel.UpdateServicioAsync(objServicioBE);
        }
        
        public WEB_Chambix.ServicioServicio.ServicioBE GetServicio(short idServicio) {
            return base.Channel.GetServicio(idServicio);
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioServicio.ServicioBE> GetServicioAsync(short idServicio) {
            return base.Channel.GetServicioAsync(idServicio);
        }
        
        public WEB_Chambix.ServicioServicio.ServicioBE[] GetAllServicio() {
            return base.Channel.GetAllServicio();
        }
        
        public System.Threading.Tasks.Task<WEB_Chambix.ServicioServicio.ServicioBE[]> GetAllServicioAsync() {
            return base.Channel.GetAllServicioAsync();
        }
    }
}
